### ISSUE TITLE
cardView作为rootView,出来的效果不是你发的图样式，图片会距离rootView有内边距

### ISSUE THREAD

**Issue by JunaYa** [shts/TriangleLabelView#1]
这样效果看起来没你原发的好看，而且这样导致triangleView的角没有被圆角，求解

**Comment by shts** [comment]
What?

**Comment by JunaYa** [comment]
Thank you open code,I learned it.Thank you!

2016-06-02 22:33 GMT+08:00 Shota Saito <notifications@github.com>:

**Comment by shts** [comment]
😃😃😃
